---
title: "Landtag"
---


Der Landtag ist das Parlament des Fürstentums Liechtenstein und damit "das gesetzmässige Organ der Gesamtheit der Landesangehörigen" ([Art. 45 Landesverfassung](https://verfassung.li/Art._45)). Von 1921 bis 1988 zählte er 15 Abgeordnete, wobei neun Sitze auf das Oberland und sechs Sitze auf das Unterland entfielen. Im Jahre 1988 wurde der Landtag nach einer vom Volk angenommenen Verfassungsänderung auf **25 Abgeordnete** erweitert (15 aus dem Oberland und 10 aus dem Unterland) ([LGBl. 1988.011](https://www.gesetze.li/chrono/1988011000)). Die Erhöhung kam erstmals bei den Landtagswahlen 1989 zur Anwendung.  

Die Berechtigung zur Wahl der Landtagsabgeordneten erfuhr im Laufe der Zeit verschiedene Änderungen. So wurde das **Wahlrechtsalter** schrittweise gesenkt, erstmals mit dem Volksrechtegesetz von 1922 von 24 auf 21 Jahre ([LGBl. 1922.028](https://www.gesetze.li/chrono/1922028000)). Eine weitere Senkung des Wahlalters von 21 auf 20 Jahre fand im Jahre 1969 statt ([LGBl. 1969.048](https://www.gesetze.li/chrono/1969048000)),  gefolgt von einer Herabsetzung auf 18 Jahre im Jahre 2000 ([LGBl. 2000.055](https://www.gesetze.li/chrono/2000055000)). Das **Frauenstimm- und -wahlrecht** in Landesangelegenheiten wurde nach der Volksabstimmung vom 29. Juni / 1. Juli 1984 eingeführt ([LGBl. 1984.027](https://www.gesetze.li/chrono/1984027000)). 

Im Jahre 1939 fand der Wechsel vom zuvor geltenden Majorz- zum **Proporzwahlrecht** statt ([LGBl. 1939.003](https://www.gesetze.li/chrono/1939003000)). Dabei galt jede eingereichte Wahlliste als Listenstimme für die betreffende Partei (Listenproporz), wobei veränderte Wahllisten der Partei mit den meisten Kandidaten auf der Liste zugesprochen wurden. Im Jahre 1973 folgte schliesslich der Wechsel vom Listen- zum **Kandidierendenproporz** ([LGBl. 1973.050](https://www.gesetze.li/konso/1973050000)). Seither entscheiden nicht mehr die Listenstimmen, sondern die Kandidierenden- und Zusatzstimmen über die Verteilung der Mandate auf die verschiedenen Parteien.   

Seit 1945 haben fünf Parteien den Einzug in den Landtag geschafft: Die beiden bürgerlichen Grossparteien **Fortschrittliche Bürgerpartei (FBP)** und **Vaterländische Union (VU)**, seit 1993 die linke Oppositionspartei **Freie Liste (FL)** sowie die beiden rechten Oppositionsparteien **DU - Die Unabhängigen für Liechtenstein** (2013-2017) und **Demokraten pro Liechtenstein (DpL)** (2021).   

Das [Liechtenstein-Institut](https://www.liechtenstein-institut.li/forschungsprojekte/abstimmungen-und-wahlen-liechtenstein#forschungsprojekt) führt seit 1997 **Umfragen zu den Landtagswahlen** durch. Entsprechende Daten sind auf der Seite "Umfragen zu den Landtagswahlen" dargestellt.  

\
\


# Literatur des Liechtenstein-Instituts

Beck, Roger (2013): [Rechtliche Ausgestaltung, Arbeitsweise und Reformbedarf des liechtensteinischen Landtags.](https://www.eliechtensteinensia.li/viewer/image/000474913/1/) Schaan: Verlag der Liechtensteinischen Akademischen Gesellschaft (Liechtenstein Politische Schriften, Bd. 53)

Frommelt, Christian; Milic, Thomas; Rochat, Philippe (2021): [Landtagswahlen 2021 – Ergebnisse der Wahlumfrage.](https://www.liechtenstein-institut.li/publikationen/frommelt-christian-milic-thomas-rochat-philippe-2021-landtagswahlen-2021-ergebnisse-der-wahlumfrage-bendern-beitraege-liechtenst) Bendern (Beiträge Liechtenstein-Institut, 49)

Marxer, Wilfried (2017): [Landtagswahlen vom 5. Februar 2017. Ergebnisse einer Umfrage.](https://www.liechtenstein-institut.li/publikationen/marxer-wilfried-2017-landtagswahlen-vom-5-februar-2017-ergebnisse-einer-umfrage-bendern-li-aktuell-12017) Bendern (LI Aktuell 1/2017)

Marxer, Wilfried (2013): [Landtagswahlen 2013 - Frauen im Fokus.](https://www.liechtenstein-institut.li/publikationen/marxer-wilfried-2013-landtagswahlen-2013-frauen-im-fokus-bendern-arbeitspapiere-liechtenstein-institut-41) Bendern (Arbeitspapiere Liechtenstein-Institut, 41)

Marxer, Wilfried (2009): [Landtagswahlen 2009: Regierungsbildung und Wählerpräferenzen in Liechtenstein.](https://www.liechtenstein-institut.li/publikationen/marxer-wilfried-2009-landtagswahlen-2009-regierungsbildung-und-wahlerpraferenzen-liechtenstein-bendern-arbeitspapiere-liechtenst) Bendern (Arbeitspapiere Liechtenstein-Institut, 23)

Marxer, Wilfried (2005): [Einflüsse der Verfassungsabstimmung auf die Landtagswahlen 2005 - Thesen, Befunde, Interpretationen. Analysen zu den Landtagswahlen 2005 in Liechtenstein (II).](https://www.liechtenstein-institut.li/publikationen/marxer-wilfried-2005-einflusse-der-verfassungsabstimmung-auf-die-landtagswahlen-2005-thesen-befunde-interpretationen-analysen-zu) Bendern (Beiträge Liechtenstein-Institut, 31)

Marxer, Wilfried (2005):[Wahlchancen von Frauen in der liechtensteinischen Politik. Analysen zu den Landtagswahlen 2005 in Liechtenstein (I).](https://www.liechtenstein-institut.li/publikationen/marxer-wilfried-2005-wahlchancen-von-frauen-der-liechtensteinischen-politik-analysen-zu-den-landtagswahlen-2005-liechtenstein-i) Bendern (Beiträge
Liechtenstein-Institut, 30)

Marxer, Wilfried (2000): [Wahlverhalten und Wahlmotive im Fürstentum Liechtenstein.](https://www.liechtenstein-institut.li/publikationen/marxer-wilfried-2000-wahlverhalten-und-wahlmotive-im-furstentum-liechtenstein-diss-univ-zurich-vaduz-verlag-der-liechtensteinisc) Diss. Univ. Zürich. Vaduz: Verlag der Liechtensteinischen Akademischen Gesellschaft (Liechtenstein Politische Schriften, Bd. 30)

Marxer, Wilfried (1997): [Landtagswahlen vom 2. Februar 1997: Wahlergebnis der Frauen. Resultate einer repräsentativen Volksbefragung und von schriftlichen Umfragen bei den Landtagskandidatinnen und den Ortsgruppenvorsitzenden der Parteien.](https://www.liechtenstein-institut.li/publikationen/marxer-wilfried-1997-landtagswahlen-vom-2-februar-1997-wahlergebnis-der-frauen-resultate-einer-reprasentativen-volksbefragung-un) (Hg. Regierung des Fürstentums Liechtenstein). Vaduz

Wille, Herbert (2015): [Die liechtensteinische Staatsordnung. Verfassungsrechtliche Grundlagen und oberste Organe.](https://www.liechtenstein-institut.li/publikationen/wille-herbert-2015-die-liechtensteinische-staatsordnung-verfassungsgeschichtliche-grundlagen-und-oberste-organe-schaan-verlag-de) Schaan: Verlag der Liechtensteinischen Akademischen Gesellschaft (Liechtenstein Politische Schriften, Bd. 57)

Vogt, Paul (2011): [Landtag.](https://historisches-lexikon.li/Landtag) In: Historisches Lexikon des Fürstentums Liechtenstein online (eHLFL).

Waschkuhn, Arno (1994): [Politisches System Liechtensteins: Kontinuität und Wandel.](https://www.liechtenstein-institut.li/publikationen/waschkuhn-arno-1994-politisches-system-liechtensteins-kontinuitat-und-wandel-vaduz-verlag-der-liechtensteinischen-akademischen-g) Vaduz: Verlag der Liechtensteinischen Akademischen Gesellschaft (Liechtenstein Politische Schriften, Bd. 18)
\
\